ラベルが存在しないのにremoveLabelを呼び出すとActionがエラーになる問題の修正
nota/.github pull request #9
Opened 2022-12-19 03:43 UTC by yuiseki

## About

- 前提：このリポジトリのActionsは、複数のリポジトリから参照されている
- このリポジトリのActionsは、Pull requestのラベル管理を自動化しているものが多い
- 「AAAが起きた時にラベルをXからYに置き換える」というActionsがいくつかあるが、存在しないラベルを削除しようとすると、そのGitHub Actionsはエラーで失敗表示になる
- CIは通っているのにラベル管理のせいで失敗表示になるのはわかりにくいし気持ち悪いので、修正したい

2022-12-19 05:11 UTC, sussan0416 requested changes
修正ありがとうございます、問題なさそうです！
1ヶ所、誤字があるようでした！変更をお願いします 🙏

2022-12-19 05:11 UTC, sussan0416 commented on .github/workflows/pr-changes-requested-replace-label.yml
> +            const UNLABEL = 'Shit It';
ここは、 Shi**p** it と思われます！ 🙏

2022-12-19 05:53 UTC, yuiseki commented on .github/workflows/pr-changes-requested-replace-label.yml
> +            const UNLABEL = 'Shit It';
おおおごめんなさいｗ

2022-12-19 05:53 UTC, yuiseki commented on .github/workflows/pr-changes-requested-replace-label.yml
> +            const UNLABEL = 'Shit It';
```suggestion
            const UNLABEL = 'Ship It';
```

2022-12-19 06:27 UTC, sussan0416 approved these changes
LGTM！ありがとうございます！！ 🙏

2022-12-20 01:55 UTC, yuiseki commented
他のリポジトリで検証したところ、try-catchではエラーを防げないことがわかりました。
GitHub Actionsの `if` と `contains` 文を使うようにしたので、再レビューお願いします。

2022-12-20 08:45 UTC, sussan0416 approved these changes
LGTMです！
if contains であれば大丈夫そうです。

try-catchでは補足できないんですね……。
たしかに iOS側のPR で、引き続き落ちていることが確認できました 🙇 
https://github.com/nota/GyazoiOS/pull/140

2022-12-20 10:33 UTC, yuiseki commented
レビューありがとうございます！マージします！

2022-12-20 10:33 UTC, merged